//! CDP-level backend operations (Layer 2 — daemon-internal).
//!
//! [`BackendOp`] represents the primitives that the daemon's Action Handler
//! compiles high-level [`Action`](super::action::Action)s into. These are
//! executed by a [`BackendSession`] implementation (Local, Extension, Cloud).
//!
//! BackendOps are **not** exposed to CLI clients and do **not** need serde.
//! The daemon owns the full lifecycle: compile Action -> sequence of BackendOps
//! -> execute via backend -> aggregate into ActionResult.

/// A CDP-level primitive operation executed against a browser backend.
///
/// The Action Handler compiles user-facing Actions into sequences of these ops.
/// For example, `Action::Click { selector }` compiles to:
/// ```text
/// GetDocument -> QuerySelector(selector) -> GetBoxModel(node_id) -> DispatchMouseEvent(x, y)
/// ```
#[derive(Debug, Clone)]
pub enum BackendOp {
    // ---- Navigation ----
    /// Navigate a target to a URL (`Page.navigate`).
    Navigate {
        /// CDP target ID.
        target_id: String,
        url: String,
    },

    // ---- JavaScript evaluation ----
    /// Evaluate a JS expression (`Runtime.evaluate`).
    Evaluate {
        target_id: String,
        expression: String,
        /// If true, evaluate returns by value (no remote object).
        return_by_value: bool,
    },

    // ---- DOM queries ----
    /// Get the document root node (`DOM.getDocument`).
    GetDocument {
        target_id: String,
    },

    /// Query a CSS selector within a node (`DOM.querySelector`).
    QuerySelector {
        target_id: String,
        node_id: i64,
        selector: String,
    },

    /// Get the box model (position/size) of a node (`DOM.getBoxModel`).
    GetBoxModel {
        target_id: String,
        node_id: i64,
    },

    // ---- Input dispatch ----
    /// Dispatch a mouse event (`Input.dispatchMouseEvent`).
    DispatchMouseEvent {
        target_id: String,
        /// Event type: "mousePressed", "mouseReleased", "mouseMoved".
        event_type: String,
        x: f64,
        y: f64,
        /// Mouse button: "left", "right", "middle".
        button: String,
        /// Number of clicks.
        click_count: i32,
    },

    /// Dispatch a key event (`Input.dispatchKeyEvent`).
    DispatchKeyEvent {
        target_id: String,
        /// Event type: "keyDown", "keyUp", "char".
        event_type: String,
        /// Key identifier (e.g. "Enter", "a").
        key: String,
        /// Text generated by the key press.
        text: String,
    },

    // ---- Capture ----
    /// Capture a screenshot as PNG (`Page.captureScreenshot`).
    CaptureScreenshot {
        target_id: String,
        /// Capture the full scrollable page (not just the viewport).
        full_page: bool,
    },

    /// Print the page to PDF (`Page.printToPDF`).
    PrintToPdf {
        target_id: String,
    },

    /// Get the accessibility tree (`Accessibility.getFullAXTree`).
    GetAccessibilityTree {
        target_id: String,
    },

    // ---- Cookies ----
    /// Get all cookies (`Network.getCookies`).
    GetCookies {
        target_id: String,
    },

    /// Set a cookie (`Network.setCookie`).
    SetCookie {
        target_id: String,
        name: String,
        value: String,
        domain: String,
        path: String,
    },

    // ---- Target management ----
    /// List all CDP targets (`Target.getTargets`).
    GetTargets,

    /// Create a new target/tab (`Target.createTarget`).
    CreateTarget {
        url: String,
        /// If set, open in this browser window.
        window_id: Option<i64>,
        /// If true, create in a new window.
        new_window: bool,
    },

    /// Close a target (`Target.closeTarget`).
    CloseTarget {
        target_id: String,
    },
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn navigate_debug_format() {
        let op = BackendOp::Navigate {
            target_id: "ABC123".into(),
            url: "https://example.com".into(),
        };
        let debug = format!("{op:?}");
        assert!(debug.contains("Navigate"));
        assert!(debug.contains("ABC123"));
    }

    #[test]
    fn clone_works() {
        let op = BackendOp::Evaluate {
            target_id: "T1".into(),
            expression: "1+1".into(),
            return_by_value: true,
        };
        let cloned = op.clone();
        match cloned {
            BackendOp::Evaluate {
                expression,
                return_by_value,
                ..
            } => {
                assert_eq!(expression, "1+1");
                assert!(return_by_value);
            }
            _ => panic!("wrong variant after clone"),
        }
    }

    #[test]
    fn dispatch_mouse_event_fields() {
        let op = BackendOp::DispatchMouseEvent {
            target_id: "T1".into(),
            event_type: "mousePressed".into(),
            x: 150.0,
            y: 300.0,
            button: "left".into(),
            click_count: 1,
        };
        match op {
            BackendOp::DispatchMouseEvent {
                x,
                y,
                click_count,
                ..
            } => {
                assert!((x - 150.0).abs() < f64::EPSILON);
                assert!((y - 300.0).abs() < f64::EPSILON);
                assert_eq!(click_count, 1);
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn create_target_with_window() {
        let op = BackendOp::CreateTarget {
            url: "about:blank".into(),
            window_id: Some(42),
            new_window: false,
        };
        match op {
            BackendOp::CreateTarget {
                url,
                window_id,
                new_window,
            } => {
                assert_eq!(url, "about:blank");
                assert_eq!(window_id, Some(42));
                assert!(!new_window);
            }
            _ => panic!("wrong variant"),
        }
    }
}
